version: '3.9'

services:
  backend:
    build: .
    container_name: pdf2excel-backend
    ports:
      - '5000:5000'
    environment:
      - SECRET_KEY=${SECRET_KEY:-super_secret_key}
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    restart: unless-stopped
